db_url: jdbc:mysql://localhost:3306/amee_profile_development
db_driver: com.mysql.jdbc.Driver
db_user: amee
db_password:

output_file: output.csv

batch_size: 50000

iterate_sql: select id from companies order by id asc

export_sql: |
  select c.* 
  from companies c
  where c.id >= ?
  and c.id <= ?
